
name: Post merge webhook for YML files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'

  workflow_dispatch:

jobs:

  trigger-webux-webhook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send API call
        run: | 
          curl \
          -XPOST \
          -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/Affirm/web-ux/dispatches \
          --data '{"event_type": "build_api_types"}'
    
